# Generated by Django 5.2.7 on 2026-04-16 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0010_remove_order_awb_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shiprocket_order_id', models.CharField(max_length=100, null=True)),
                ('shipment_id', models.CharField(max_length=100, null=True)),
                ('courier_name', models.CharField(max_length=100, null=True)),
                ('courier_id', models.IntegerField(null=True)),
                ('awb_code', models.CharField(max_length=100, null=True)),
                ('tracking_url', models.URLField(null=True)),
                ('status', models.CharField(default='created', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
    ]
