# Generated by Django 5.2.7 on 2026-04-14 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_shipment_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order1',
        ),
        migrations.DeleteModel(
            name='Shipment',
        ),
    ]
