# Generated by Django 5.2.7 on 2026-04-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_shipment_order_delete_order1_delete_shipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(default='Name'),
        ),
    ]
