# Generated by Django 5.2.7 on 2026-04-15 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orderitem_product_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_order_c_cd5b49_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_user_id_a87c6f_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_created_0e92de_idx',
        ),
    ]
