# Generated by Django 5.2.7 on 2026-04-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_awb_code_order_shiprocket_shipment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='tracking_id',
            new_name='shiprocket_order_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shipping_status',
            new_name='shiprocket_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='courier_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivered_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_attempts',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_failure_reason',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipment_created_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipped_at',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='refunded_quantity',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='return_reason',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_code',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('razorpay', 'Razorpay'), ('cod', 'COD')], default='razorpay', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], default='confirmed', max_length=20),
        ),
    ]
