# Generated by Django 5.2.7 on 2026-04-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_rename_tracking_id_order_shiprocket_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_status',
            field=models.CharField(default='created', max_length=100),
        ),
    ]
