# Generated by Django 5.2.7 on 2026-04-16 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_tracking_last_update_order_tracking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='awb_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shiprocket_order_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shiprocket_shipment_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shiprocket_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tracking_last_update',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tracking_status',
        ),
    ]
